(G-code generated by FlatCAM Evo vUnstable - Version Date: 2023/6/31)

(Name: Encoders-LCD.drl_cnc)
(Type: G-code from Excellon)
(Units: MM)

(Created on Friday, 14 February 2025 at 19:01)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware. No M6 command.)


(TOOLS DIAMETER: )
(Tool: 3 -> Dia: 1.1)

(FEEDRATE Z: )
(Tool: 3 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 3 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 3 -> Z_Cut: -1.7)

(Tools Offset: )
(Tool: 3 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 3 -> Z_Move: 2)

(Z Start: None mm)
(Z End: 15 mm)
(X,Y End: None mm)
(Steps per circle: 16)
(Steps per circle: 16)
(Preprocessor Excellon: GRBL_11_no_M6)

(X range:  -45.6000 ...   45.6000  mm)
(Y range:  -36.9430 ...   33.6000  mm)

(Spindle Speed: 900 RPM)
G21
G90
G17
G94


G01 F300.00
G00 Z2.0000

M03 S900
G00 X3.0800 Y-20.3980
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X3.0800 Y-24.8980
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X-3.4200 Y-24.8980
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X-3.4200 Y-20.3980
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X-29.8630 Y21.1550
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X-29.8630 Y25.6550
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X-36.3630 Y25.6550
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X-36.3630 Y21.1550
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X29.3600 Y21.1500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X29.3600 Y25.6500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X35.8600 Y25.6500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X35.8600 Y21.1500
G01 Z-1.7000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00


