(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: lcd-ht16k33.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Sunday, 25 May 2025 at 22:09)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.6)
(Tool: 2 -> Dia: 0.8)
(Tool: 3 -> Dia: 1.19)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 300)
(Tool: 3 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.8)
(Tool: 2 -> Z_Cut: -1.8)
(Tool: 3 -> Z_Cut: -1.8)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Steps per circle: 64)
(Preprocessor Excellon: GRBL_11_no_M6)

(X range:    3.2060 ...   52.6500  mm)
(Y range:    0.9440 ...   26.5750  mm)

(Spindle Speed: 1000 RPM)
G21
G90
G17
G94


G01 F300.00

M5             
G00 Z15.0000
G00 X0.0000 Y0.0000                
T1
(MSG, Change to Tool Dia = 0.6000 ||| Total drills for tool T1 = 14)
M0
G00 Z15.0000
        
G01 F300.00
M03 S1000
G00 X39.1930 Y5.3080
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X39.1930 Y1.2440
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X34.4940 Y3.5300
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X34.4940 Y5.5620
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.4930 Y5.6890
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X14.9360 Y3.5300
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X6.6810 Y5.9430
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X3.5060 Y5.9430
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X25.7310 Y20.5480
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.7470 Y19.5320
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X28.0170 Y18.1350
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X32.5890 Y18.1350
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X33.2240 Y20.5480
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X34.3670 Y19.5320
G01 Z-1.8000
G01 Z0
G00 Z2.0000
M05
G00 Z0.50


