(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: lcd-ht16k33-PTH.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Tuesday, 27 May 2025 at 17:03)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.6)
(Tool: 2 -> Dia: 0.8)
(Tool: 3 -> Dia: 1.19)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 300)
(Tool: 3 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.8)
(Tool: 2 -> Z_Cut: -1.8)
(Tool: 3 -> Z_Cut: -1.8)

(Tools Offset: )
(Tool: 2 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Steps per circle: 64)
(Preprocessor Excellon: GRBL_11_no_M6)

(X range:   11.9440 ...   37.5750  mm)
(Y range:   -2.6500 ...   46.7940  mm)

(Spindle Speed: 1000 RPM)
G21
G90
G17
G94


G01 F300.00

M5             
G00 Z15.0000
G00 X0.0000 Y0.0000                
T2
(MSG, Change to Tool Dia = 0.8000 ||| Total drills for tool T2 = 22)
M0
G00 Z15.0000
        
G01 F300.00
M03 S1000
G00 X27.1600 Y-2.2500
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.1600 Y0.2900
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.1600 Y2.8300
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.1600 Y5.3700
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.1600 Y7.9100
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.1600 Y10.4500
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.1600 Y30.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.1600 Y32.5400
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.1600 Y35.0800
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.1600 Y37.6200
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.1600 Y40.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.1600 Y42.7000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.0000 Y40.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.0000 Y37.6200
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.0000 Y35.0800
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.0000 Y32.5400
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.0000 Y30.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.0000 Y7.9100
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.0000 Y5.3700
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.0000 Y2.8300
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.0000 Y0.2900
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.0000 Y-2.2500
G01 Z-1.8000
G01 Z0
G00 Z2.0000
M05
G00 Z0.50


