(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: lcd-ht16k33.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Sunday, 25 May 2025 at 22:09)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.6)
(Tool: 2 -> Dia: 0.8)
(Tool: 3 -> Dia: 1.19)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 300)
(Tool: 3 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.8)
(Tool: 2 -> Z_Cut: -1.8)
(Tool: 3 -> Z_Cut: -1.8)

(Tools Offset: )
(Tool: 2 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Steps per circle: 64)
(Preprocessor Excellon: GRBL_11_no_M6)

(X range:    3.2060 ...   52.6500  mm)
(Y range:    0.9440 ...   26.5750  mm)

(Spindle Speed: 1000 RPM)
G21
G90
G17
G94


G01 F300.00

M5             
G00 Z15.0000
G00 X0.0000 Y0.0000                
T2
(MSG, Change to Tool Dia = 0.8000 ||| Total drills for tool T2 = 22)
M0
G00 Z15.0000
        
G01 F300.00
M03 S1000
G00 X52.2500 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X49.7100 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X47.1700 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X44.6300 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X42.0900 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X39.5500 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X20.0000 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.4600 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X14.9200 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X12.3800 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X9.8400 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X7.3000 Y16.1600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X9.8400 Y6.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X12.3800 Y6.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X14.9200 Y6.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X17.4600 Y6.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X20.0000 Y6.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X42.0900 Y6.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X44.6300 Y6.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X47.1700 Y6.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X49.7100 Y6.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X52.2500 Y6.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
M05
G00 Z0.50


