(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: lcd-ht16k33.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Wednesday, 28 May 2025 at 19:16)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.6)
(Tool: 2 -> Dia: 0.8)
(Tool: 3 -> Dia: 1.19)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 300)
(Tool: 3 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.8)
(Tool: 2 -> Z_Cut: -1.8)
(Tool: 3 -> Z_Cut: -1.8)

(Tools Offset: )
(Tool: 2 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 15.0 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Steps per circle: 64)
(Preprocessor Excellon: GRBL_11_no_M6)

(X range:   16.4250 ...   42.8690  mm)
(Y range:    6.9000 ...   52.6500  mm)

(Spindle Speed: 1000 RPM)
G21
G90
G17
G94


G01 F300.00

M5             
G00 Z15.0000
G00 X0.0000 Y0.0000                
T2
(MSG, Change to Tool Dia = 0.8000 ||| Total drills for tool T2 = 22)
M0
G00 Z15.0000
        
G01 F300.00
M03 S1000
G00 X37.0000 Y52.2500
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X37.0000 Y49.7100
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X37.0000 Y47.1700
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X37.0000 Y44.6300
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X37.0000 Y42.0900
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X37.0000 Y20.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X37.0000 Y17.4600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X37.0000 Y14.9200
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X37.0000 Y12.3800
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X37.0000 Y9.8400
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y7.3000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y9.8400
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y12.3800
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y14.9200
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y17.4600
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y20.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y39.5500
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y42.0900
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y44.6300
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y47.1700
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y49.7100
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X26.8400 Y52.2500
G01 Z-1.8000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00


