(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: encoders-i2c.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Wednesday, 30 April 2025 at 19:57)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.6)
(Tool: 2 -> Dia: 1.0)
(Tool: 3 -> Dia: 1.19)
(Tool: 4 -> Dia: 2.6)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 300)
(Tool: 3 -> Feedrate: 300)
(Tool: 4 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.8)
(Tool: 2 -> Z_Cut: -1.8)
(Tool: 3 -> Z_Cut: -1.8)
(Tool: 4 -> Z_Cut: -1.8)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)
(Tool: 4 -> Z_Move: 2)

(Z Toolchange: 15.0 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 15.0 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Steps per circle: 64)
(Preprocessor Excellon: GRBL_11_no_M6)

(X range:  -34.9100 ...   34.8900  mm)
(Y range:  -22.7500 ...   20.8250  mm)

(Spindle Speed: 900 RPM)
G21
G90
G17
G94


G01 F300.00

M5             
G00 Z15.0000
G00 X0.0000 Y0.0000                
T1
(MSG, Change to Tool Dia = 0.6000 ||| Total drills for tool T1 = 4)
M0
G00 Z15.0000
        
G01 F300.00
M03 S900
G00 X6.7110 Y11.6540
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X6.7110 Y8.7950
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-8.7830 Y11.7810
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-4.0840 Y11.5090
G01 Z-1.8000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00


