(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: encoders-i2c.drl_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Wednesday, 30 April 2025 at 19:58)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.6)
(Tool: 2 -> Dia: 1.0)
(Tool: 3 -> Dia: 1.19)
(Tool: 4 -> Dia: 2.6)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 300)
(Tool: 3 -> Feedrate: 300)
(Tool: 4 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.8)
(Tool: 2 -> Z_Cut: -1.8)
(Tool: 3 -> Z_Cut: -1.8)
(Tool: 4 -> Z_Cut: -1.8)

(Tools Offset: )
(Tool: 2 -> Offset Z: 0.0)
(Tool: 3 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)
(Tool: 4 -> Z_Move: 2)

(Z Toolchange: 15.0 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 15.0 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Steps per circle: 64)
(Preprocessor Excellon: GRBL_11_no_M6)

(X range:  -34.9100 ...   34.8900  mm)
(Y range:  -22.7500 ...   20.8250  mm)

(Spindle Speed: 900 RPM)
G21
G90
G17
G94


G01 F300.00

M5             
G00 Z15.0000
G00 X0.0000 Y0.0000                
T2
(MSG, Change to Tool Dia = 1.0000 ||| Total drills for tool T2 = 19)
M0
G00 Z15.0000
        
G01 F300.00
M03 S900
G00 X30.4900 Y15.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X25.4900 Y15.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X3.8000 Y20.2300
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X1.2600 Y20.2300
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-1.2800 Y20.2300
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-3.8200 Y20.2300
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-25.5100 Y15.5900
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-30.5100 Y15.5900
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-30.5100 Y1.0900
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-28.0100 Y1.0900
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-25.5100 Y1.0900
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-2.5100 Y-22.2500
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X2.4900 Y-22.2500
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-2.5100 Y-7.7500
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X-0.0100 Y-7.7500
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X2.4900 Y-7.7500
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X25.4900 Y1.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X27.9900 Y1.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X30.4900 Y1.0000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
M05
G00 Z15.00


